name: ci-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: setup-go

      - name: checkout code into runner
        uses: actions/checkout@v2
      
      - name: Test
        run: make runtest