name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: setup-go

      - name: checkout code into runner
        uses: actions/checkout@v3
      
      - name: Test
        run: make runtest