name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: apart
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: setup-go

      - name: Checkout code into runner
        uses: actions/checkout@v3

      - name: Install golang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migration up
        run: migrate -path db/migration -database "postgresql://postgres:password@localhost:5432/parcel_management?sslmode=disable" -verbose up
      
      - name: Test
        run: make runtest